apiVersion: v1
kind: ConfigMap
metadata:
  name: dongle-configmap
data:
  DB_HOST: 81.70.154.116
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongle-deploy
spec:
  replicas: 3
  minReadySeconds: 10
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: dongle-deploy
  template:
    metadata:
      labels:
        app: dongle-deploy
    spec:
      imagePullSecrets:
        - name: coding-docker
      containers:
      - name: dongle-deploy
        image: hj212223/dongle:v0.0.99
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: dongle-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: dongle-service
spec:
  selector:
    app: dongle-deploy
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dongle-ingress
  labels:
    name: dongle-ingress
spec:
  rules:
  - host: 81.70.154.116
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dongle-service
            port: 
              number: 3000





